### PR TITLE
Fix build issues, add .gitignore

### LINKED ISSUE #33: legacy_api not building
### What steps can be done to repeat the issue on a test server?
1. git clone
2. import maven project
3. 'package' task fails

### What is supposed to happen instead?
3. 'package' builds .jar

### Versions/Files

Towny Version (use '/towny v' in game) : N/A
TownyFlight Version : 1.4.7-latest
Link to pastebin.com with full server startup from the latest.log : N/A
Link to pastebin.com with TownyFlight config.yml : N/A

I'm opening this to document the issue behind my PR.

### PR DESCRIPTION
**Pull request by jackstrosahl**
Fixes #33 

Needed to switch to Java 8 in pom.xml, and add Towny and WarsForTowny as dependencies.  Right now these are just .jars, I don't think there's a repo for them.

I also added a .gitignore.

### CODE REVIEW

**Comment by LlmDl** [comment]
You're working on the legacy branch because you're using MC 1.12?

**Comment by jackstrosahl** [comment]
> You're working on the legacy branch because you're using MC 1.12?

Yup.  I was trying to reproduce a bug, couldn't actually do that but figured this small fix would be useful.

**Comment by LlmDl** [comment]
Ok, so you know, there's a preview build of 0.96.1.10 made for 1.12 on the discord's MC-1_12-prereleases channel. As of that build officially coming out when we do our next release, the legacy branch will not be needed.

**Comment by jackstrosahl** [comment]
Thanks!  I'll have to join the Discord.

**Comment by LlmDl** [comment]
Give me a @LlmDl when you join and I'll assign you a role.

**Pull request merged**
